// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATjD-W194P8h4lwT2Fh944y0UdTmGAEjU',
    appId: '1:1022818895411:web:8dd29ba7579d8509328546',
    messagingSenderId: '1022818895411',
    projectId: 'antony-flutterapp-dev',
    authDomain: 'antony-flutterapp-dev.firebaseapp.com',
    storageBucket: 'antony-flutterapp-dev.firebasestorage.app',
    measurementId: 'G-ZT5DN6L909',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3IdNdphjsdBddtzao1sFikHKtPlJNN4',
    appId: '1:1022818895411:android:af4e62a153f6e267328546',
    messagingSenderId: '1022818895411',
    projectId: 'antony-flutterapp-dev',
    storageBucket: 'antony-flutterapp-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClluPvt4IBp-QYF8U36S3Sd0Llw6EJX5Q',
    appId: '1:1022818895411:ios:32805a96bf044531328546',
    messagingSenderId: '1022818895411',
    projectId: 'antony-flutterapp-dev',
    storageBucket: 'antony-flutterapp-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClluPvt4IBp-QYF8U36S3Sd0Llw6EJX5Q',
    appId: '1:1022818895411:ios:32805a96bf044531328546',
    messagingSenderId: '1022818895411',
    projectId: 'antony-flutterapp-dev',
    storageBucket: 'antony-flutterapp-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATjD-W194P8h4lwT2Fh944y0UdTmGAEjU',
    appId: '1:1022818895411:web:b80b2b80e336fbf6328546',
    messagingSenderId: '1022818895411',
    projectId: 'antony-flutterapp-dev',
    authDomain: 'antony-flutterapp-dev.firebaseapp.com',
    storageBucket: 'antony-flutterapp-dev.firebasestorage.app',
    measurementId: 'G-424WZV0NDE',
  );
}
